- name: Provision ec2 instances based on the environment
  hosts: localhost
  connection: local
  gather_facts: False
 
  tasks:
  - name: launch ansible cloudformation example
    cloudformation:
      stack_name: "ansible-cloudformation-f5"
      state: "present"
      ec2_access_key: "{{ ec2_access_key }}"
      ec2_secret_key: "{{ ec2_secret_key }}"
      region: "eu-west-1"
      disable_rollback: true
      template_url: "https://s3.amazonaws.com/f5-cft/f5-existing-stack-bigiq-1nic-bigip.template <https://s3.amazonaws.com/f5-cft/f5-existing-stack-bigiq-1nic-bigip.template>"
      template_parameters:
        bigipExternalSecurityGroup: "sg-c5d917bd"
        bigiqPasswordS3Arn: "arn:aws:s3:::dualbigips/bigiq-thing"
        Vpc: "vpc-e5f05e82"
        bigiqLicensePoolName: "aws_lic_pool"
        bigiqAddress: "172.31.9.14"
        sshKey: "Amazon Key Pair For Demos"
        subnet1Az1: "subnet-281fbc4f"
        bigiqUsername: "admin"
      tags:
        Stack: "ansible-f5-cloudformation"
